/**
 * @file ui.h
 * @brief The public API (bridge) for interacting with the generated LVGL UI.
 *
 * This module decouples the main application logic from the low-level UI objects
 * generated by EEZ Studio, providing a clean interface for updates.
 */

#ifndef UI_BRIDGE_H
#define UI_BRIDGE_H

#include "shared_structures.h"
#include <stdint.h>

/**
 * @brief Initializes the UI by calling the init function from the generated code.
 *
 * This should be called once from setup() after the LVGL driver is ready.
 */
void ui_bridge_init();

/**
 * @brief Updates all relevant UI elements based on the latest status from LCNC.
 * @param data The LcncStatusPacket received from the communication layer.
 */
void ui_bridge_update_from_lcnc(const LcncStatusPacket &data);

/**
 * @brief Updates UI elements that depend on local HMI state (selectors).
 * @param active_axis The currently selected axis index (0-5).
 * @param selected_step The currently selected jog step index.
 */
void ui_bridge_update_jog_selectors(uint8_t active_axis, uint8_t selected_step);

/**
 * @brief Applies runtime configuration (e.g., from the web UI) to the screen.
 * @param cfg The PendantWebConfig object containing the configuration to apply.
 */
void ui_bridge_apply_config(const PendantWebConfig &cfg);

#endif // UI_BRIDGE_H